language: python
python:
  - "3.6"
install:
  - pip install requests
  - pip install pandas
  - pip install numpy
  - pip install --upgrade watson-developer-cloud
script:
  - pytest
cache:
    pip
    directories:
        - node_modules # NPM packages
